create type "public"."playback_policy" as enum ('signed', 'public');

create table "public"."mux_assets" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text not null,
    "video_upload_id" uuid not null,
    "playback_id" text,
    "playback_policy" playback_policy not null
);


alter table "public"."mux_assets" enable row level security;

CREATE UNIQUE INDEX mux_assets_pkey ON public.mux_assets USING btree (id);

alter table "public"."mux_assets" add constraint "mux_assets_pkey" PRIMARY KEY using index "mux_assets_pkey";

alter table "public"."mux_assets" add constraint "mux_assets_video_upload_id_fkey" FOREIGN KEY (video_upload_id) REFERENCES storage.objects(id) ON DELETE CASCADE not valid;

alter table "public"."mux_assets" validate constraint "mux_assets_video_upload_id_fkey";

grant delete on table "public"."mux_assets" to "anon";

grant insert on table "public"."mux_assets" to "anon";

grant references on table "public"."mux_assets" to "anon";

grant select on table "public"."mux_assets" to "anon";

grant trigger on table "public"."mux_assets" to "anon";

grant truncate on table "public"."mux_assets" to "anon";

grant update on table "public"."mux_assets" to "anon";

grant delete on table "public"."mux_assets" to "authenticated";

grant insert on table "public"."mux_assets" to "authenticated";

grant references on table "public"."mux_assets" to "authenticated";

grant select on table "public"."mux_assets" to "authenticated";

grant trigger on table "public"."mux_assets" to "authenticated";

grant truncate on table "public"."mux_assets" to "authenticated";

grant update on table "public"."mux_assets" to "authenticated";

grant delete on table "public"."mux_assets" to "service_role";

grant insert on table "public"."mux_assets" to "service_role";

grant references on table "public"."mux_assets" to "service_role";

grant select on table "public"."mux_assets" to "service_role";

grant trigger on table "public"."mux_assets" to "service_role";

grant truncate on table "public"."mux_assets" to "service_role";

grant update on table "public"."mux_assets" to "service_role";



